window.PROJECTS = [
  {
    id: "mjflood",
    title: "MJ Flood",
    category: "Brand & Digital",
    tag: "Project",
    shortDesc: "Complete digital transformation for Ireland's leading technology provider",
    fullDesc: "A complete digital transformation for Ireland's largest indigenous supplier of office technology, managed print services, security systems, and coffee solutions — unifying 90 years of heritage under a bold new digital presence.",
    client: "MJ Flood Group",
    year: "2024",
    location: "Dublin, Ireland",
    services: "Brand Identity, Web Design, Digital Strategy, UX/UI",
    cardSize: "tall",
    thumbnail: "images/mjflood/Mjflood-M.mp4",
    gallery: [
      { type: "video", src: "images/mjflood/Mjflood-M.mp4" },
      { type: "image", src: "images/mjflood/asset 1.webp" },
      { type: "image", src: "images/mjflood/asset 2.webp" },
      { type: "image", src: "images/mjflood/asset 3.webp" },
      { type: "image", src: "images/mjflood/asset 4.webp" },
      { type: "image", src: "images/mjflood/asset 5.webp" },
      { type: "image", src: "images/mjflood/asset 6.webp" },
      { type: "image", src: "images/mjflood/asset 7.webp" },
      { type: "image", src: "images/mjflood/asset 8.webp" },
      { type: "image", src: "images/mjflood/asset 9.webp" },
      { type: "image", src: "images/mjflood/asset 10.webp" },
      { type: "image", src: "images/mjflood/asset 11.webp" },
      { type: "image", src: "images/mjflood/asset 12.webp" },
      { type: "image", src: "images/mjflood/asset 13.webp" },
      { type: "image", src: "images/mjflood/asset 14.webp" },
      { type: "image", src: "images/mjflood/asset 15.webp" },
      { type: "image", src: "images/mjflood/asset 16.webp" },
      { type: "image", src: "images/mjflood/asset 17.webp" },
      { type: "image", src: "images/mjflood/asset 18.webp" },
      { type: "image", src: "images/mjflood/asset 19.webp" },
      { type: "image", src: "images/mjflood/asset 20.webp" }
    ],
    featured: true
  },
  {
    id: "engineers-ireland",
    title: "Engineers Ireland",
    category: "Web Design",
    tag: "Project",
    shortDesc: "Professional web presence for Ireland's leading engineering body",
    fullDesc: "A comprehensive digital transformation for Ireland's professional engineering body, creating a modern, accessible digital platform that serves as the definitive hub for Ireland's engineering community.",
    client: "Engineers Ireland",
    year: "2024",
    location: "Dublin, Ireland",
    services: "Web Design, UX Strategy, Development, Content Architecture",
    cardSize: "standard",
    thumbnail: "images/engineers-ireland/iPhone-mockup-eng irl.mp4",
    gallery: [
      { type: "video", src: "images/engineers-ireland/iPhone-mockup-eng irl.mp4" },
      { type: "video", src: "images/engineers-ireland/engineers-ireland-website.mp4" },
      { type: "video", src: "images/engineers-ireland/logo engineers.mp4" },
      { type: "image", src: "images/engineers-ireland/asset 1.webp" },
      { type: "image", src: "images/engineers-ireland/asset 2.webp" },
      { type: "image", src: "images/engineers-ireland/asset 3.webp" },
      { type: "image", src: "images/engineers-ireland/asset 4.webp" },
      { type: "image", src: "images/engineers-ireland/asset 5.webp" },
      { type: "image", src: "images/engineers-ireland/asset 6.webp" },
      { type: "image", src: "images/engineers-ireland/asset 7.webp" },
      { type: "image", src: "images/engineers-ireland/asset 8.webp" },
      { type: "image", src: "images/engineers-ireland/asset 9.webp" },
      { type: "image", src: "images/engineers-ireland/asset 10.webp" },
      { type: "image", src: "images/engineers-ireland/asset 11.webp" },
      { type: "image", src: "images/engineers-ireland/asset 12.webp" },
      { type: "image", src: "images/engineers-ireland/asset 13.webp" },
      { type: "image", src: "images/engineers-ireland/asset 14.webp" },
      { type: "image", src: "images/engineers-ireland/asset 15.webp" }
    ],
    featured: true
  },
  {
    id: "turmec",
    title: "Turmec",
    category: "Brand & Digital",
    tag: "Project",
    shortDesc: "Bold digital rebrand for Ireland's leading recycling technology company",
    fullDesc: "A comprehensive brand and digital overhaul for Turmec, Ireland's foremost designer and manufacturer of recycling and waste processing equipment. The project unified their industrial expertise with a modern, authoritative digital presence that reflects their innovation in sustainable technology.",
    client: "Turmec",
    year: "2024",
    location: "Tipperary, Ireland",
    services: "Brand Identity, Web Design, Digital Strategy, Content",
    cardSize: "standard",
    thumbnail: "images/turmec/Turmec.mp4",
    gallery: [
      { type: "video", src: "images/turmec/Turmec.mp4" },
      { type: "image", src: "images/turmec/turmec-web-and-mob-scaled.png" },
      { type: "image", src: "images/turmec/turmec-web-scaled.png" },
      { type: "image", src: "images/turmec/turmec-web2-scaled.png" },
      { type: "image", src: "images/turmec/Turmec-Expo.jpg" },
      { type: "image", src: "images/turmec/Turmec-ID-Card-Holder-scaled.jpg" },
      { type: "image", src: "images/turmec/Turmec-Safety-BG-4k.jpg" },
      { type: "image", src: "images/turmec/Turmec-high-vis-and-hardhat.jpg" }
    ],
    featured: true
  },
  {
    id: "celsius",
    title: "Celsius",
    category: "Brand & Digital",
    tag: "Project",
    shortDesc: "Dynamic brand campaign and digital content for a global energy drink",
    fullDesc: "A high-impact brand campaign and digital content suite for Celsius, delivering bold advertising creative across multiple formats. From motion-driven social ads to large-scale digital placements, every asset was crafted to capture attention and drive brand recognition.",
    client: "Celsius",
    year: "2024",
    location: "Dublin, Ireland",
    services: "Brand Identity, Motion Design, Digital Advertising, Content",
    cardSize: "tall",
    thumbnail: "images/celsius/logo-intro.mov",
    gallery: [
      { type: "video", src: "images/celsius/logo-intro.mov" },
      { type: "video", src: "images/celsius/Celsius-ad-16x9-1.mp4" },
      { type: "video", src: "images/celsius/Celsius-ad-9x16-1.mp4" },
      { type: "video", src: "images/celsius/Celsius-ad-treadmill-ad.mp4" },
      { type: "image", src: "images/celsius/ad-placement2-scaled.webp" },
      { type: "image", src: "images/celsius/ad-placement3-scaled.webp" },
      { type: "image", src: "images/celsius/ad-placement4-scaled.webp" },
      { type: "image", src: "images/celsius/ad-placement5.1-scaled.webp" }
    ],
    featured: true
  },
  {
    id: "blanchardstown",
    title: "Blanchardstown Centre",
    category: "Brand & Digital",
    tag: "Project",
    shortDesc: "Reimagining the digital experience for Ireland's largest shopping destination",
    fullDesc: "A full-scale digital transformation for Blanchardstown Centre, one of Ireland's largest and most visited retail destinations. The project delivered a seamless digital experience connecting shoppers with stores, events, and services — driving footfall and engagement across every channel.",
    client: "Blanchardstown Centre",
    year: "2024",
    location: "Dublin, Ireland",
    services: "Brand Identity, Web Design, Digital Strategy, UX/UI",
    cardSize: "standard",
    thumbnail: "images/blanchardstown-shopping-center/BLANCHARDSTOWN.mp4",
    gallery: [
      { type: "video", src: "images/blanchardstown-shopping-center/BLANCHARDSTOWN.mp4" },
      { type: "image", src: "images/blanchardstown-shopping-center/asset 1.webp" },
      { type: "image", src: "images/blanchardstown-shopping-center/asset 2.webp" },
      { type: "image", src: "images/blanchardstown-shopping-center/asset 3.webp" },
      { type: "image", src: "images/blanchardstown-shopping-center/asset 4.webp" },
      { type: "image", src: "images/blanchardstown-shopping-center/asset 5.webp" },
      { type: "image", src: "images/blanchardstown-shopping-center/asset 6.webp" },
      { type: "image", src: "images/blanchardstown-shopping-center/asset 7.webp" },
      { type: "image", src: "images/blanchardstown-shopping-center/asset 8.webp" },
      { type: "image", src: "images/blanchardstown-shopping-center/asset 9.webp" }
    ],
    featured: false
  },
  {
    id: "liffey-meats",
    title: "Liffey Meats",
    category: "Brand & Digital",
    tag: "Project",
    shortDesc: "Premium meat brand digital presence and e-commerce platform",
    fullDesc: "A complete brand refresh and digital transformation for Ireland's premium meat provider, featuring an immersive shopping experience and content-rich storytelling about sourcing and quality.",
    client: "Liffey Meats",
    year: "2024",
    location: "Dublin, Ireland",
    services: "Brand Identity, Web Design, E-Commerce, Content Strategy",
    cardSize: "standard",
    thumbnail: "images/liffey-meats/Liffy-1.mp4",
    gallery: [
      { type: "video", src: "images/liffey-meats/Liffy-1.mp4" },
      { type: "image", src: "images/liffey-meats/asset 1.webp" },
      { type: "image", src: "images/liffey-meats/asset 2.webp" },
      { type: "image", src: "images/liffey-meats/asset 3.webp" },
      { type: "image", src: "images/liffey-meats/asset 4.webp" },
      { type: "image", src: "images/liffey-meats/asset 5.webp" },
      { type: "image", src: "images/liffey-meats/asset 6.webp" },
      { type: "image", src: "images/liffey-meats/asset 7.webp" },
      { type: "image", src: "images/liffey-meats/asset 8.webp" },
      { type: "image", src: "images/liffey-meats/asset 9.webp" },
      { type: "image", src: "images/liffey-meats/asset 10.webp" },
      { type: "image", src: "images/liffey-meats/asset 11.webp" },
      { type: "image", src: "images/liffey-meats/asset 12.webp" },
      { type: "image", src: "images/liffey-meats/asset 13.webp" },
      { type: "image", src: "images/liffey-meats/asset 14.webp" },
      { type: "image", src: "images/liffey-meats/asset 15.webp" },
      { type: "image", src: "images/liffey-meats/asset 16.webp" }
    ],
    featured: false
  },
  {
    id: "whatsexposed",
    title: "WhatsExposed",
    category: "Brand & Digital",
    tag: "Project",
    shortDesc: "Bold brand identity and digital campaign for an investigative media platform",
    fullDesc: "A striking brand identity and multi-channel digital campaign for WhatsExposed, an investigative media platform. From animated brand reveals to social content and immersive web experiences, every touchpoint was designed to command attention and build credibility in a crowded media landscape.",
    client: "WhatsExposed",
    year: "2025",
    location: "Dublin, Ireland",
    services: "Brand Identity, Motion Design, Web Design, Social Content",
    cardSize: "full",
    thumbnail: "images/whatsexposed/WhatsExposed animation.mp4",
    gallery: [
      { type: "video", src: "images/whatsexposed/WhatsExposed animation.mp4" },
      { type: "video", src: "images/whatsexposed/social posts.mov" },
      { type: "video", src: "images/whatsexposed/web pages.mov" },
      { type: "image", src: "images/whatsexposed/openart-image_61DWJ3yD_1775250089925_raw.webp" },
      { type: "image", src: "images/whatsexposed/openart-image_67ftaqa__1775254632869_raw.webp" },
      { type: "image", src: "images/whatsexposed/openart-image_8DvMIjb7_1775248848320_raw.webp" },
      { type: "image", src: "images/whatsexposed/openart-image_Mi4r-Fbj_1775252287000_raw.webp" },
      { type: "image", src: "images/whatsexposed/openart-image_Qy47_ZyP_1775253039220_raw.webp" },
      { type: "image", src: "images/whatsexposed/openart-image_V7WmE9H1_1775252989593_raw.webp" },
      { type: "image", src: "images/whatsexposed/openart-image_X5ncexup_1775252243462_raw.webp" },
      { type: "image", src: "images/whatsexposed/openart-image_hplpyVAO_1775254232179_raw.webp" },
      { type: "image", src: "images/whatsexposed/openart-image_n26tXemr_1775248902938_raw.webp" },
      { type: "image", src: "images/whatsexposed/openart-image_okfHQ8Cs_1775254086267_raw.webp" },
      { type: "image", src: "images/whatsexposed/openart-image_qWGEJIAA_1775249053974_raw.webp" },
      { type: "image", src: "images/whatsexposed/openart-image_rF_oci9h_1775252851838_raw.webp" }
    ],
    featured: false
  },
  {
    id: "brand-strategy",
    title: "Brand Strategy",
    category: "Brand Identity",
    tag: "Experience",
    shortDesc: "Strategic brand positioning, visual systems, and guidelines that drive recognition and trust across every touchpoint.",
    cardSize: "text",
    featured: true
  },
  {
    id: "digital-craft",
    title: "Digital Craft",
    category: "Web Design",
    tag: "Skill",
    shortDesc: "Bespoke websites and digital products built with meticulous attention to detail, performance, and user experience.",
    cardSize: "text",
    featured: false
  }
];
