# -*- coding: utf-8 -*-
# KD Lab: experiments and tools shown on the Playground page.
# Local experiments live under /lab/<slug>/. "url" overrides the link (external projects).
# "build" is kept for reference only, the playground stopped printing it in July 2026.

EXPERIMENTS = [
{
 "slug": "lumora",
 "num": "01",
 "title": "Lumora",
 "tagline": "A hero you watch from a train",
 "desc": "A full-screen hero for an invented mindfulness app, framed as a carriage window. Four films run past outside and the interface sits on the glass in front of them, so changing scene crossfades the world rather than the page. The bright scene turns the whole block of copy to ink, because white type has nothing to hold onto against snow.",
 "tags": ["Generative film", "Glass UI", "React"],
 "build": "The four films are stacked full-screen and crossfaded on opacity over a second, each one looped forward and back so nothing ever cuts. The carriage is a single transparent PNG laid over the top, bobbing six pixels every three seconds and held at a slight scale so no edge is ever exposed. One CSS variable carries the ink colour, so the switch to the snow moves badge, heading, subtext, field and scene labels together instead of element by element. React, TypeScript and Tailwind, built with Vite.",
},
{
 "slug": "aurai",
 "num": "02",
 "title": "Aurai",
 "tagline": "A hero section for a brand that does not exist",
 "desc": "A full-screen landing page for an invented always-on wellness companion. One film runs behind everything and the interface sits on top in glass, with no dark overlay anywhere. The shot was directed to leave the left of frame empty so the type has somewhere to live.",
 "tags": ["Generative film", "Glass UI", "React"],
 "build": "The film came out of OpenArt: a still from GPT Image 2 animated with Seedance 2.0, then looped forward and back so the visor unwinds instead of cutting. It was shot twice, 16:9 and 9:16, and the page loads whichever cut suits the screen. React, TypeScript and Tailwind, built with Vite.",
},
{
 "slug": "lithos",
 "num": "03",
 "title": "Lithos",
 "tagline": "A spotlight that x-rays the page",
 "desc": "A hero section for an invented geology brand. Two photographs of the same cliff sit exactly on top of each other, and a soft circular spotlight follows the cursor, cutting a window through the top one so the seams below read like an x-ray of the rock.",
 "tags": ["Canvas masking", "Cursor reveal", "React"],
 "build": "A radial gradient is painted into an offscreen canvas every frame, then handed to CSS as a mask image on the second layer. The cursor is eased with a lerp so the light lags slightly behind the pointer. React, TypeScript and Tailwind, built with Vite. Both stone photographs were generated in OpenArt.",
},
{
 "slug": "vaultshield",
 "num": "04",
 "title": "VaultShield",
 "tagline": "A hero for a password manager that does not exist",
 "desc": "A full-screen hero for an invented password manager. The film plays behind everything with no scrim over it, because the shot was directed to keep its left third empty, so dark type sits straight on the picture. The icons live inside the headline as words rather than beside it, so they wrap with the line.",
 "tags": ["Generative film", "Framer Motion", "React"],
 "build": "The film came out of OpenArt: a still from Nano Banana Pro animated with Seedance 2.0, then looped forward and back so the glass keys never cut. Heading, subtext and button share one fadeUp variant staggered 0.15 seconds apart, and the mobile sheet slides in on the same easing curve. React, TypeScript, Tailwind and Framer Motion, built with Vite.",
},
{
 "slug": "drift",
 "num": "05",
 "title": "Drift",
 "tagline": "A landing page that stays quiet",
 "desc": "A single page for an invented ADHD-friendly planner. The hero is one held shot of morning light, the cream section rides up over it by the exact radius of its own corners, and the feature cards slide in one at a time against a fixed backdrop while the index on the left keeps pace with where you are.",
 "tags": ["Scroll cards", "Generative film", "React"],
 "build": "Two intersection observers run the right-hand column: one at 60 percent to say which card you are on, one at 15 percent to fire each entrance once and leave it. All four films were made in OpenArt, stills from Nano Banana Pro animated with Seedance 2.0, then looped forward and back so nothing ever cuts. React, TypeScript and Tailwind, built with Vite.",
},
{
 "slug": "securify",
 "num": "06",
 "title": "Securify",
 "tagline": "A headline placed rather than typeset",
 "desc": "A full-screen hero for an invented data-security platform. The headline is cut into three words and pinned to different corners of the frame, so the eye steps down the page and the film keeps showing through the gaps between them. Nothing sits on a panel: the type, the stats and the navigation all lie straight on the picture.",
 "tags": ["Display type", "Generative film", "React"],
 "build": "The film is a Seedance 2.0 shot from OpenArt, a close tracking shot of a snowboarder at golden hour, looped forward and back so it never cuts. It plays at close to its own exposure: rather than grade the picture flat so white type can survive it, the shading is pulled in from the four edges where the words actually sit and the middle of frame is left as shot. The camera keeps moving, so the type also carries a wide soft shadow that vanishes over the dark and holds the letterforms together when a flare sweeps under them. React, TypeScript and Tailwind, built with Vite.",
},
{
 "slug": "clubos",
 "num": "07",
 "title": "ClubOS",
 "tagline": "One app, every club's colours",
 "desc": "A management app for grassroots football clubs, shown here as Firhouse Carmel FC. Fixtures, tables, squads, team selection and availability polls, all running on the club's real Amateur Football League season. The club is not hard coded: crest, colours, grounds and teams are data, so a club signs up, picks two colours, and the whole app arrives in their identity.",
 "tags": ["Product design", "White label", "Real data"],
 "build": "Colour is one pair of CSS variables mixed through every surface with color-mix, and the accent decides its own text colour by luminance, so a club can pick navy and yellow or green and white and nothing needs restyling. Standings and results were scraped from the league's own site, and each opponent carries its real crest. Vanilla HTML, CSS and JavaScript, no framework, installable as a PWA.",
 "url": "https://kieranduffy87.github.io/firhouse-carmel-fc/?showcase",
 "external": True,
},
{
 "slug": "dental",
 "num": "08",
 "title": "Dental Health",
 "tagline": "One photograph, cut across nine cards",
 "desc": "A landing page for a clinic that does not exist. Every card in a section is a window onto the same photograph: each one measures where it sits and shifts the picture by exactly that much, so the image runs unbroken behind the whole mosaic while the cards keep their own rounded corners.",
 "tags": ["Masked cards", "Generative photography", "React"],
 "build": "The picture is scaled to the section height and offset per card, so a narrow window sees a much smaller slice than a wide one. The focal point slides left as that slice narrows, which keeps the headline on clear ground at any size. All five photographs were made in OpenArt with Nano Banana Pro and art directed around where the type lands. React, TypeScript and Tailwind, built with Vite.",
},
{
 "slug": "imagination-explorer",
 "num": "09",
 "title": "The Imagination Explorer",
 "tagline": "A scroll-film for a children's brand",
 "desc": "A promo site built as one continuous scroll-film: the story scrubs frame by frame as you move down the page, with type and colour cued to the film rather than layered over it.",
 "tags": ["Scroll film", "Brand site", "Art direction"],
 "build": "Scroll position drives film playback directly, so the page and the footage share one timeline. Built as a standalone site, no framework.",
 "url": "lab/imagination-explorer/index.html",
},
{
 "slug": "aurora",
 "num": "10",
 "title": "Aurora",
 "tagline": "Colour that breathes",
 "desc": "A live WebGL gradient with no images at all: fractal noise, domain-warped twice, pushed through a brand palette and steered by the pointer. Runs on a single fullscreen triangle.",
 "tags": ["WebGL", "GLSL", "Generative"],
 "build": "Hand-written fragment shader (fbm + domain warping). Falls back to an animated CSS field where WebGL is unavailable.",
},
{
 "slug": "reveal",
 "num": "11",
 "title": "Reveal",
 "tagline": "An index that shows its hand",
 "desc": "The agency-list problem: a list scans faster than a grid but hides the work. Here the preview tracks the cursor with inertia, skewing to its own velocity, while the rest of the index dims away.",
 "tags": ["Hover reveal", "Inertia", "Velocity skew"],
 "build": "Preview position lerps behind the pointer; frame skew and scale are derived from per-frame delta.",
},
{
 "slug": "pillgrid",
 "num": "12",
 "title": "PILLGRID",
 "tagline": "Any video, rebuilt in pills",
 "desc": "A real-time video filter that rebuilds footage as a matrix of pill-shaped dots, like a physical LED display. Load a clip or use your camera, then tune grid density, pill shape, colour and bleed live.",
 "tags": ["WebGL", "Video filter", "Real time"],
 "build": "Every frame is sampled to a grid in a fragment shader and redrawn as pills. Single file, no build step, runs entirely in the browser.",
 "url": "https://kieranduffy87.github.io/pillgrid/",
 "external": True,
},
]

TOOLS = [
{
 "title": "KD Logomotion",
 "url": "https://kieranduffy87.github.io/kd-logomotion/",
 "desc": "Drop in a logo and get a vertical brand film back. The mark locks dead centre and never moves while twenty-four worlds cut past behind it on the beat, drawn scenes and graded photography alternating. Swap any background for your own, grade it, and export an MP4 with sound without leaving the browser.",
 "tags": ["Canvas", "WebCodecs", "Web Tool"],
 "preview": "video",
 "slug": "kd-logomotion",
},
{
 "title": "KD Design System",
 "url": "https://kieranduffy87.github.io/kd-design-system/",
 "desc": "My own brand as a working system: tokens, type scale, colour, components and usage rules, documented and published so every project I build starts from the same foundation.",
 "tags": ["Design system", "Tokens", "Documentation"],
 "preview": "video",
 "slug": "kd-design-system",
},
{
 "title": "SVG to 3D",
 "url": "https://kieranduffy87.github.io/svg-to-3d/",
 "desc": "Turn any SVG into an interactive 3D object in the browser. Pick materials, colours, extrusion depth and animation, then share the result with a single link.",
 "tags": ["Three.js", "Web Tool"],
 "preview": "3d",
},
{
 "title": "Designer Tools",
 "url": "https://kieranduffy87.github.io/designer-tools/",
 "desc": "A growing collection of small utilities for everyday design work. Mesh gradients, colour pickers and more, all in one place.",
 "tags": ["Toolkit", "Utilities"],
 "preview": "mesh",
},
]
